# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Qt_test\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form1):
        Form1.setObjectName("Form1")
        Form1.resize(1260, 618)
        Form1.setAutoFillBackground(False)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(Form1)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Cover/image/Cover.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalWidget = QtWidgets.QWidget(Form1)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.verticalWidget)
        self.label_4.setMinimumSize(QtCore.QSize(104, 25))
        self.label_4.setMaximumSize(QtCore.QSize(104, 25))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Logo/image/Logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.BodyLabel = BodyLabel(self.verticalWidget)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout.addWidget(self.BodyLabel)
        self.LineEdit_2 = LineEdit(self.verticalWidget)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.verticalLayout.addWidget(self.LineEdit_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.BodyLabel_2 = BodyLabel(self.verticalWidget)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.verticalLayout.addWidget(self.BodyLabel_2)
        self.PasswordLineEdit = PasswordLineEdit(self.verticalWidget)
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.verticalLayout.addWidget(self.PasswordLineEdit)
        spacerItem3 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.PrimaryPushButton = PrimaryPushButton(self.verticalWidget)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.verticalLayout.addWidget(self.PrimaryPushButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.verticalWidget)

        self.retranslateUi(Form1)
        QtCore.QMetaObject.connectSlotsByName(Form1)

    def retranslateUi(self, Form1):
        _translate = QtCore.QCoreApplication.translate
        Form1.setWindowTitle(_translate("Form1", "Login"))
        self.BodyLabel.setText(_translate("Form1", "User Name:"))
        self.BodyLabel_2.setText(_translate("Form1", "Password:"))
        self.PrimaryPushButton.setText(_translate("Form1", "Login"))
from qfluentwidgets import BodyLabel, LineEdit, PasswordLineEdit, PrimaryPushButton
import image_source_rc
